PimDoos/ha-sessy

- README.md
- custom_components/sessy/sensor.py
- custom_components/sessy/sessyentity.py
> Use native attributes for entities in update flow

- custom_components/sessy/sessyentity.py
> Fix regression from #2: Entities not updating

- custom_components/sessy/__init__.py
- custom_components/sessy/util.py
> Fix #14 clear cache trackers on reload

- custom_components/sessy/manifest.json
- custom_components/sessy/update.py
> Fix #16 Update notifications when none available

- custom_components/sessy/sensor.py
- custom_components/sessy/util.py
> Add P1 status to SessyP1Meter sensors

- INFO.md
- README.md
- custom_components/sessy/manifest.json
- custom_components/sessy/number.py
- custom_components/sessy/select.py
- custom_components/sessy/sensor.py
- custom_components/sessy/sessyentity.py
- custom_components/sessy/strings.json
- custom_components/sessy/translations/en.json
- custom_components/sessy/translations/nl.json
- custom_components/sessy/util.py
> Move state values to strings.json

- custom_components/sessy/sensor.py
> Fix #26: Correct unit for phase current

- README.md
- custom_components/sessy/manifest.json
> Housekeeping

- .github/dependabot.yml
- .github/workflows/hacs.yaml
- .github/workflows/hassfest.yaml
- custom_components/sessy/const.py
- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
- custom_components/sessy/sessyentity.py
- custom_components/sessy/strings.json
- custom_components/sessy/translations/en.json
- custom_components/sessy/translations/nl.json
- custom_components/sessy/util.py
Adds frequency, system state details, and more system state options.
> Add Sessy firmware v1.2.0 features

- custom_components/sessy/sensor.py
- custom_components/sessy/util.py
* custom_components/sessy/sensor.py:
* custom_components/sessy/util.py:
> Use divide instead of devide, removed trailing whitespaces

- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
- custom_components/sessy/sessyentity.py
- custom_components/sessy/update.py
- custom_components/sessy/util.py
Adds more P1 data (added in Sessy v1.3.3 / SessyPy v0.0.8)
Fixes #31 software version on device page does not match after updating
> Add v1.3.3 features and bugfixes

- custom_components/sessy/config_flow.py
- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
- custom_components/sessy/strings.json
- custom_components/sessy/translations/en.json
- custom_components/sessy/translations/nl.json
- custom_components/sessy/util.py
Adds support for mDNS (added in Sessy firmware v1.3.8)
Bumps sessypy to 0.0.10 (resolves issues with python 3.11 compatibility in longer running systems due to missing dependency pinning)
Add separate charge/discharge power to help with temporary energy sensors
> Updates for v0.3.2

- custom_components/sessy/__init__.py
- custom_components/sessy/button.py
- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
- custom_components/sessy/update.py
Fix #51: Add Sessy CT Meter
Add restart button as diagnostic entity
> Add Sessy CT meter and restart button

- custom_components/sessy/manifest.json
- custom_components/sessy/number.py
> Add noise level control

- custom_components/sessy/__init__.py
- custom_components/sessy/button.py
- custom_components/sessy/manifest.json
- custom_components/sessy/number.py
- custom_components/sessy/select.py
- custom_components/sessy/sessyentity.py
- custom_components/sessy/time.py
- custom_components/sessy/update.py
Use Home Assistant exceptions to generate more readable logs
> Improve log readability

- custom_components/sessy/manifest.json
Fixes unexpected sensor states after network issues. Connection timeout is now 5 seconds instead of 5 minutes.
> Bump SessyPy to 0.1.5

- custom_components/sessy/manifest.json
Adds firmware 1.5.4 system state OVERRIDE_BATTERY_UNDERVOLTAGE by @MartijnCharged
> Bump sessypy to 0.1.6

- custom_components/sessy/manifest.json
- custom_components/sessy/number.py
- custom_components/sessy/sensor.py
Adds P1 gas meter data available in Sessy firmware 1.5.5
> Add Gas meter

- custom_components/sessy/sensor.py
> Disable wifi RSSI sensor when API is null

- custom_components/sessy/strings.json
- custom_components/sessy/translations/en.json
- custom_components/sessy/translations/nl.json
> Added support for strategy SessyConnect

- README.md
- custom_components/sessy/const.py
- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
- custom_components/sessy/util.py
Fix #85
- Add dynamic mode power schedule sensor
- Add energy price schedule sensor
> Implement schedule API: Dynamic mode schedule and energy prices

- custom_components/sessy/manifest.json
Activates SessyConnect strategy in dropdown
> Bump sessypy to 0.1.10

- custom_components/sessy/__init__.py
- custom_components/sessy/config_flow.py
- custom_components/sessy/manifest.json
- custom_components/sessy/number.py
- custom_components/sessy/sessyentity.py
- custom_components/sessy/strings.json
- custom_components/sessy/switch.py
- custom_components/sessy/translations/en.json
- custom_components/sessy/translations/nl.json
Add support for ECO power strategy
> Add ECO strategy

- custom_components/sessy/switch.py
> Fix #94 async bug in switch turn on/off

- custom_components/sessy/__init__.py
- custom_components/sessy/manifest.json
https://developers.home-assistant.io/blog/2024/06/12/async_forward_entry_setups
> Replace deprecated setup code

- README.md
- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
- custom_components/sessy/util.py
Closes #8 
Firmware dependency: at least 1.7.2
> Add energy sensors

- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
> Add Inverter Current sensor

- custom_components/sessy/config_flow.py
https://developers.home-assistant.io/blog/2025/01/15/service-info
> Use relocated zeroconf ServiceInfo model

- custom_components/sessy/coordinator.py
- custom_components/sessy/manifest.json
- custom_components/sessy/number.py
- custom_components/sessy/switch.py
Fixes #119 
Regression in 0.8.0
> Fix system settings and power strategy entities

- custom_components/sessy/manifest.json
- custom_components/sessy/sensor.py
Adds new sensors for interfacing with the DC port.
> Add External Power & Pack Voltage sensors (fw 1.9.1)

- custom_components/sessy/coordinator.py
- custom_components/sessy/manifest.json
- custom_components/sessy/util.py
Should fix #118, #121, #126, #127
> Improve exception handling & fetch serial number on setup
